spring:
  application:
    name: hello-spring-cloud-zuul


server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: spring-cloud-web-ribbon01
    api-b:
      path: /api/b/**
      serviceId: spring-cloud-web-feign
